-- ******************************************************************************************
-- Usuário sys 
-- ******************************************************************************************
CREATE TABLE ALUNO (
	ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
	NOME VARCHAR(50),
	PRIMARY KEY(ID)
)

SELECT * FROM ALUNO;

--------------------------------------------------------------------------------------------
-- ALTER TABLE
ALTER TABLE ALUNO ADD IDADE INT;

--------------------------------------------------------------------------------------------
-- CREATE VIEW
CREATE OR REPLACE VIEW VIEWDADOSALUNO AS
	SELECT 'ALUNO: ' || NOME || ' DE ID ' || TO_CHAR(ID) || ' TEM ' || TO_CHAR(IDADE) || ' ANOS.' AS DADOS FROM ALUNO;

SELECT * FROM VIEWDADOSALUNO;

-- DROP VIEW
DROP VIEW VIEWDADOSALUNO;

--------------------------------------------------------------------------------------------
-- SYNONYMS
-- Criação do sinônimo
SELECT * FROM ALL_SYNONYMS  WHERE SYNONYM_NAME = 'ALUNO'; -- Listagem dos sinônimos

DROP SYNONYM HR.ALUNO;

CREATE OR REPLACE SYNONYM HR.ALUNO FOR ALUNO;

CREATE OR REPLACE SYNONYM HR.VIEWDADOSALUNO FOR VIEWDADOSALUNO;

--------------------------------------------------------------------------------------------
-- GRANTS

SELECT * FROM DBA_TAB_PRIVS WHERE TABLE_NAME = 'ALUNO'; -- Listagem das grants

REVOKE SELECT ON ALUNO FROM HR; -- Remover grant

GRANT SELECT ON ALUNO TO HR;
GRANT INSERT ON ALUNO TO HR;
GRANT UPDATE ON ALUNO TO HR;
GRANT DELETE ON ALUNO TO HR;
GRANT ALTER ON ALUNO TO HR;

GRANT ALL ON ALUNO TO HR; -- GRANT de todos os privilégios

GRANT ALL ON VIEWDADOSALUNO TO HR;

REVOKE ALL ON ALUNO FROM HR; -- Remove todos os privilégios

--------------------------------------------------------------------------------------------
-- ALL_OBJECTS
SELECT * FROM ALL_OBJECTS WHERE OBJECT_NAME = 'VIEWDADOSALUNO';

-- ******************************************************************************************
-- Outro usuário 
-- ******************************************************************************************
SELECT * FROM ALUNO;

INSERT INTO ALUNO (NOME) VALUES ('LUCAS');
INSERT INTO ALUNO (NOME) VALUES ('MACEDO');
INSERT INTO ALUNO (NOME) VALUES ('JOSÉ');
INSERT INTO ALUNO (NOME) VALUES ('JOE');
INSERT INTO ALUNO (NOME) VALUES ('THOR');
INSERT INTO ALUNO (NOME) VALUES ('SILVIO');

DELETE FROM ALUNO WHERE NOME = 'SILVIO';

---------------------------------------------------------------------------------------------
-- UPDATE TABLE
UPDATE ALUNO SET IDADE = 23 WHERE ID = 1;
UPDATE ALUNO SET IDADE = 35 WHERE ID = 2;
UPDATE ALUNO SET IDADE = 32 WHERE ID = 3;
UPDATE ALUNO SET IDADE = 23 WHERE ID = 4;
UPDATE ALUNO SET IDADE = 20 WHERE ID = 5;

---------------------------------------------------------------------------------------------
-- VIEW
SELECT * FROM VIEWDADOSALUNO;




